# Generated by Django 6.0 on 2026-01-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='製品名')),
                ('description', models.TextField(verbose_name='製品説明')),
                ('price', models.IntegerField(max_length=100, verbose_name='価格')),
            ],
            options={
                'verbose_name_plural': '製品一覧',
            },
        ),
    ]
